## This will destroy all compute VMs
- name: Destroy Compute VMs if they exist
  community.proxmox.proxmox_kvm:
    api_host: "{{ proxmox.api_host }}"
    api_user: "{{ proxmox.api_user }}"
    #api_token_id: "{{ proxmox_secrets.api_token_id }}"
    #api_token_secret: "{{ proxmox_secrets.api_token_secret }}"
    api_password: "{{ proxmox_secrets.api_password }}"
    name: "{{ item.name }}"
    node: "{{ proxmox.node }}"
    vmid: "{{ item.id }}"
    state: absent
  when:
    - cleanupFull | bool
    - nodeNetworkInfo.computes is defined
    - nodeNetworkInfo.computes | length > 0
  with_items: 
   - "{{ nodeNetworkInfo.computes }}"