---
# this role creates base files dir, downloads and sets up the OCP or OKD clients on the bastion and localhost if localhost is linux

- name: Get remote user home directory
  ansible.builtin.shell: "echo $HOME"
  register: remote_home
  changed_when: false
  become: false

- name: Set absolute path for bastion directory
  ansible.builtin.set_fact:
    bastion_dir_absolute: "{{ remote_home.stdout }}/ocp-ansible-proxmox"

- name: make working dir
  ansible.builtin.file:
    path: "{{ bastion_dir_absolute }}"
    state: directory
    mode: '0755'
  become: false


- name: make subdirs
  ansible.builtin.file:
    path: "{{ bastion_dir_absolute }}/{{ item }}"
    state: directory
    mode: '0755'
  become: false
  loop:
  - clients
  - dependencies
  - conf


- name: Get OC clients, extracts, copy to usr-local-bin
  block:
    - name: Fetch from URL
      get_url:
        url: "{{ fullUrls.client }}"
        dest: "{{ bastion_dir_absolute }}/clients/{{ dep.client }}"
        checksum: "sha256:{{ fullUrls.sha256url }}"
      register: client_download
      until: client_download is succeeded
      retries: 3


    - name: Extract clients
      unarchive:
        src: "{{ bastion_dir_absolute }}/clients/{{ dep.client }}"
        dest: "{{ bastion_dir_absolute }}/clients/"
        creates: "{{ bastion_dir_absolute }}/clients/oc"
        remote_src: yes
        list_files: yes


    - name: Copy to usr-local-bin
      ansible.builtin.copy:
        src: "{{ bastion_dir_absolute }}/clients/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        remote_src: yes
        mode: '0755'
        owner: root
        group: root
      become: yes
      become_user: root
      loop:
      - oc
      - kubectl
        

- name: Get OC Installer, extracts, copy to usr-local-bin
  block:
    - name: Fetch from URL
      get_url:
        url: "{{ fullUrls.installer }}"
        dest: "{{ bastion_dir_absolute }}/clients/{{ dep.installer }}"
        checksum: "sha256:{{ fullUrls.sha256url }}"
      register: installer_download
      until: installer_download is succeeded
      retries: 3
    
    - name: Extract installer
      unarchive:
        src: "{{ bastion_dir_absolute }}/clients/{{ dep.installer }}"
        dest: "{{ bastion_dir_absolute }}/clients/"
        creates: "{{ bastion_dir_absolute }}/clients/openshift-installer"        
        remote_src: yes
        list_files: yes

    - name: Copy to usr-local-bin
      ansible.builtin.copy:
        src: "{{ bastion_dir_absolute }}/clients/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        remote_src: yes
        mode: '0755'
        owner: root
        group: root
      become: yes
      become_user: root
      loop:
      - openshift-install

