---
- name: Stop Control Plane VMs if they exist
  community.proxmox.proxmox_kvm:
    api_host: "{{ proxmox.api_host }}"
    api_user: "{{ proxmox.api_user }}"
    #api_token_id: "{{ proxmox_secrets.api_token_id }}"
    #api_token_secret: "{{ proxmox_secrets.api_token_secret }}"
    api_password: "{{ proxmox_secrets.api_password }}"
    name: "{{ item.name }}"
    node: "{{ proxmox.node }}"
    vmid: "{{ item.id }}"
    state: stopped
    timeout: 150
  when: fullWipe | bool
  register: controlplane_stop_result
  failed_when:
    - controlplane_stop_result is failed
    - "'does not exist' not in (controlplane_stop_result.msg | default(''))"
  with_items:
   - "{{ nodeNetworkInfo.controlplanes }}"

- name: Destroy Control Plane VMs if they exist
  community.proxmox.proxmox_kvm:
    api_host: "{{ proxmox.api_host }}"
    api_user: "{{ proxmox.api_user }}"
    #api_token_id: "{{ proxmox_secrets.api_token_id }}"
    #api_token_secret: "{{ proxmox_secrets.api_token_secret }}"
    api_password: "{{ proxmox_secrets.api_password }}"
    name: "{{ item.name }}"
    node: "{{ proxmox.node }}"
    vmid: "{{ item.id }}"
    state: absent
  when: fullWipe | bool
  register: controlplane_destroy_result
  failed_when:
    - controlplane_destroy_result is failed
    - "'does not exist' not in (controlplane_destroy_result.msg | default(''))"
  with_items:
   - "{{ nodeNetworkInfo.controlplanes }}"

# Create ControlPlane VMs
- name: Create ControlPlane VMs
  community.proxmox.proxmox_kvm:
    api_host: "{{ proxmox.api_host }}"
    api_user: "{{ proxmox.api_user }}"
    #api_token_id: "{{ proxmox_secrets.api_token_id }}"
    #api_token_secret: "{{ proxmox_secrets.api_token_secret }}"
    api_password: "{{ proxmox_secrets.api_password }}"
    name: "{{ item.name }}.{{ openshift.cluster.name }}"
    node: "{{ proxmox.node }}"
    vmid: "{{ vmTemplate.id }}"
    newid: "{{ item.id }}"
    clone: "{{ vmTemplate.name }}"
    # Cannot do link clones with scsi0
    # full: no
    net:
      net0: 'virtio={{ item.MAC }},bridge={{ vmNet.ifName }}'
    agent: yes
    args: "-fw_cfg name=opt/com.coreos/config,file={{ files.proxmoxDir }}/ignitions/{{ openshift.cluster.name }}/master.ign"
    serial:
      serial0: socket
    state: present      
    timeout: 300
  register: controlplane_vms_info
  with_items:
   - "{{ nodeNetworkInfo.controlplanes }}"

- name: Update Control Plane VM hardware configuration
  community.proxmox.proxmox_kvm:
    api_host: "{{ proxmox.api_host }}"
    api_user: "{{ proxmox.api_user }}"
    api_password: "{{ proxmox_secrets.api_password }}"
    vmid: "{{ item.id }}"
    node: "{{ proxmox.node }}"
    cores: "{{ controlPlaneSizing.cores }}"
    memory: "{{ controlPlaneSizing.mem }}"
    update: yes
  with_items:
    - "{{ nodeNetworkInfo.controlplanes }}"

- name: Create NIC net0 targeting the vm by id
  community.proxmox.proxmox_nic:
    api_host: "{{ proxmox.api_host }}"
    api_user: "{{ proxmox.api_user }}"
    #api_token_id: "{{ proxmox_secrets.api_token_id }}"
    #api_token_secret: "{{ proxmox_secrets.api_token_secret }}"
    api_password: "{{ proxmox_secrets.api_password }}"
    vmid: "{{ item.id }}"
    interface: net0
    bridge: "{{ vmNet.ifName }}"
    mac: "{{ item.MAC }}"
  register: controlplanes_nics_set
  with_items:
   - "{{ nodeNetworkInfo.controlplanes }}"

# - name: View returned Control Plane VM creation info
#   debug:
#     var: controlplane_vms_info

- name: Resize control-plane nodes disks
  community.proxmox.proxmox_disk:
    api_host: "{{ proxmox.api_host }}"
    api_user: "{{ proxmox.api_user }}"
    api_password: "{{ proxmox_secrets.api_password }}"
    vmid: "{{ item.id }}"
    disk: scsi0
    size: "{{ vm_disk_size }}"
    state: resized
  with_items:
    - "{{ nodeNetworkInfo.controlplanes }}"

- name: Start Control Plane VMs after all configuration is complete
  community.proxmox.proxmox_kvm:
    api_host: "{{ proxmox.api_host }}"
    api_user: "{{ proxmox.api_user }}"
    api_password: "{{ proxmox_secrets.api_password }}"
    vmid: "{{ item.id }}"
    node: "{{ proxmox.node }}"
    state: started
    timeout: 60
  with_items:
    - "{{ nodeNetworkInfo.controlplanes }}"
  when: auto_start_vms | default(false) | bool
